### ISSUE TITLE
what is your project torch version?

### ISSUE THREAD

**Issue by wangyuuu** [dvlab-research/ECCV22-P3AFormer-Tracking-Objects-as-Pixel-wise-Distributions#3]
when i run bash configs/standard/v100_mot17_fine_tune_mot17.sh DCNv2 need torch==1.7.0 but dectron2 needs torch >1.8.0, so how can I start training?

**Comment by sjtuytc** [comment]
We tested on Pytorch==1.9.0+cu111, detectron2 == 0.6.0 and torchvision==0.10.0+cu111. Other versions might work as well.
Here is the printed env list:
> absl-py==0.11.0
addict==2.4.0
aiohttp==3.7.3
antlr4-python3-runtime==4.8
appdirs==1.4.4
argcomplete==2.0.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
async-timeout==3.0.1
attrs==20.3.0
awscli==1.22.21
backcall==0.2.0
beautifulsoup4 @ file:///tmp/build/80754af9/beautifulsoup4_1601924105527/work
black==21.4b2
bleach==4.1.0
boto3==1.20.21
botocore==1.23.21
brotlipy==0.7.0
cached-property==1.5.2
cachetools==4.2.0
certifi==2021.10.8
cffi @ file:///tmp/build/80754af9/cffi_1606255099073/work
chardet==3.0.4
click==8.0.3
cloudpickle==2.0.0
colorama==0.4.3
conda==4.9.2
conda-build==3.18.11
conda-package-handling @ file:///tmp/build/80754af9/conda-package-handling_1603018138503/work
correlation-cuda==0.0.0
crowdposetools==2.0
cryptography @ file:///tmp/build/80754af9/cryptography_1607635305226/work
cycler==0.10.0
Cython==0.29.21
cython-bbox==0.1.3
-e git+https://github.com/jinfagang/DCNv2_latest.git@fa9b2fd740ced2a22e0e7e913c3bf3934fd08098#egg=DCNv2
debugpy==1.5.1
decorator==4.4.2
defusedxml==0.7.1
descartes==1.1.0
detectron2 @ git+https://github.com/facebookresearch/detectron2.git@e1166a16aa8504ceadba86de04d79256f0784451
docutils==0.15.2
easydict==1.9
entrypoints==0.3
fairscale==0.1.4
filelock==3.0.12
filterpy==1.4.5
fire==0.4.0
flake8==3.8.4
flake8-import-order==0.18.1
fsspec==0.8.5
future==0.18.2
fvcore==0.1.5.post20211023
gdown==4.2.0
glob2==0.7
google-auth==1.24.0
google-auth-oauthlib==0.4.2
grpcio==1.34.0
h5py==3.6.0
hydra-core==1.1.1
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
imageio==2.9.0
importlib-metadata==3.3.0
importlib-resources==5.4.0
iniconfig==1.1.1
iopath==0.1.9
ipykernel==6.6.1
ipython==7.31.0
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets==7.6.5
jedi==0.17.0
Jinja2==2.11.2
jmespath==0.10.0
joblib==1.0.1
json-tricks==3.15.5
jsonschema==4.3.3
jupyter==1.0.0
jupyter-client==7.1.0
jupyter-console==6.4.0
jupyter-core==4.9.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
kiwisolver==1.3.1
lap==0.4.0
libarchive-c==2.9
llvmlite==0.36.0
loguru==0.5.3
Markdown==3.3.3
MarkupSafe @ file:///tmp/build/80754af9/markupsafe_1594371495811/work
matplotlib==3.3.3
matplotlib-inline==0.1.3
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0
motmetrics==1.2.0
multidict==5.1.0
MultiScaleDeformableAttention==1.0
mypy-extensions==0.4.3
nbclient==0.5.9
nbconvert==6.4.0
nbformat==5.1.3
nest-asyncio==1.5.4
networkx==2.5.1
ninja==1.10.2.3
notebook==6.4.6
numba==0.53.1
numpy==1.21.5
nuscenes-devkit==1.1.9
oauthlib==3.1.0
olefile==0.46
omegaconf==2.1.1
opencv-contrib-python==3.4.2.17
opencv-python==3.4.2.17
packaging==20.8
pandas==1.2.0
pandocfilters==1.5.0
panopticapi @ git+https://github.com/cocodataset/panopticapi.git@7bb4655548f98f3fedc07bf37e9040a992b054b0
parso @ file:///tmp/build/80754af9/parso_1607623074025/work
pathspec==0.9.0
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow @ file:///tmp/build/80754af9/pillow_1603822253009/work
pkginfo==1.6.1
pluggy==0.13.1
portalocker==2.3.2
progress==1.5
prometheus-client==0.12.0
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1602688806899/work
protobuf==3.14.0
psutil @ file:///tmp/build/80754af9/psutil_1598370249042/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1605560620615/work/dist/ptyprocess-0.6.0-py2.py3-none-any.whl
py==1.10.0
py-cpuinfo==7.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycocotools @ git+https://github.com/cocodataset/cocoapi.git@8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9#subdirectory=PythonAPI
pycodestyle==2.6.0
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pydot==1.4.2
pyflakes==2.2.0
Pygments @ file:///tmp/build/80754af9/pygments_1607368905949/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
pyparsing==2.4.7
pyquaternion==0.9.9
pyrsistent==0.18.0
PySocks @ file:///tmp/build/80754af9/pysocks_1594394576006/work
pytest==6.2.1
pytest-benchmark==3.2.3
python-dateutil==2.8.1
pytorch-lightning==1.1.5
pytz @ file:///tmp/build/80754af9/pytz_1606604771399/work
PyWavelets==1.1.1
PyYAML==5.4.1
pyzmq==22.3.0
qtconsole==5.2.2
QtPy==2.0.0
regex==2021.11.10
requests @ file:///tmp/build/80754af9/requests_1608241421344/work
requests-oauthlib==1.3.0
rsa==4.6
ruamel-yaml==0.15.87
s3transfer==0.5.0
scikit-image==0.18.1
scikit-learn==0.22.2
scipy==1.5.4
seaborn==0.11.2
Send2Trash==1.8.0
Shapely==1.8.0
six @ file:///tmp/build/80754af9/six_1605205313296/work
sklearn==0.0
soupsieve @ file:///tmp/build/80754af9/soupsieve_1607965878077/work
submitit==1.4.1
tabulate==0.8.9
tensorboard==2.4.0
tensorboard-plugin-wit==1.7.0
tensorboardX==2.4.1
termcolor==1.1.0
terminado==0.12.1
testpath==0.5.0
thop==0.0.31.post2005241907
threadpoolctl==2.1.0
tifffile==2021.4.8
timm==0.3.4
toml==0.10.2
torch==1.9.0+cu111
torch-dct==0.1.5
torchaudio==0.9.0
torchvision==0.10.0+cu111
tornado==6.1
tqdm @ file:///tmp/build/80754af9/tqdm_1607369919789/work
traitlets==5.1.1
typed-ast==1.5.1
typing-extensions==3.7.4.3
urllib3 @ file:///tmp/build/80754af9/urllib3_1606938623459/work
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.2
xmltodict==0.12.0
yacs==0.1.8
yapf==0.32.0
yarl==1.6.3
-e /data/zelinbytetrack
zipp==3.4.0
